# ============================================================================
#                      Copyright 2016-2020 Gennaro Prota
#
#                   Licensed under the 3-Clause BSD License.
#              (See accompanying file 3_CLAUSE_BSD_LICENSE.txt or
#               <https://opensource.org/licenses/BSD-3-Clause>.)
# ____________________________________________________________________________

root         := ../..

source_files := line_up.cpp
include $(root)/makefile/executable.mk
